name: AroundHome deploy to EKS
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        # Step 1: Checkout Code
        - name: Checkout Code
          uses: actions/checkout@v3
    
        # Step 2: Set up Docker
        - name: Log in to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
    
        # Step 3: Build and Push Docker Image
        - name: Build and Push Docker Image
          run: |
            docker build -t ${{ secrets.DOCKER_USERNAME }}/hello-world:latest .
            docker push ${{ secrets.DOCKER_USERNAME }}/hello-world:latest
    
        # Step 4: Configure AWS Credentials
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v3
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}
    
        # Step 5: Install kubectl
        - name: Install kubectl
          uses: azure/setup-kubectl@v3
          with:
            version: 'latest'
    
        # Step 6: Update kubeconfig for EKS
        - name: Update kubeconfig
          run: |
            aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name ${{ secrets.CLUSTER_NAME }}
    
        # Step 7: Install Helm
        - name: Install Helm
          uses: azure/setup-helm@v3
          with:
            version: 'latest'
    

        # Step 8: Create Namespace if Not Exists
        - name: Create Namespace
          run: |
            kubectl get namespace aroundhome || kubectl create namespace aroundhome

        # Step 9: Deploy Helm Chart
        - name: Deploy Helm Chart
          run: |
            helm upgrade --install hello-world hello-world-helm \
            --namespace aroundhome \
            --wait
